"""
Django settings for proceg project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import json
from re import S
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

with open(os.path.join('scripts', 'config.json')) as f:
    CONFIG = json.load(f)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CONFIG['SECRET_KEY']

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = CONFIG['DEBUG']

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'procead.apps.ProceadConfig',
    'Acesso_Restrito.apps.AcessoRestritoConfig',
    'Almoxarifado.apps.AlmoxarifadoConfig',
    'Curso.apps.CursoConfig',
    'Financeiro.apps.FinanceiroConfig',
    'Polo.apps.PoloConfig',
    'Viagens.apps.ViagensConfig',
    'Ticket.apps.TicketConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Adiciona ao Django funções características do postgres como queries ignorando acentuação que usaremos
    'django.contrib.postgres',
    # Biblioteca para criar e validar models de CPF e CNPJ
    'localflavor',
    # Biblioteca para auxiliar nas filtragens das listas
    'django_filters',
    # Biblioteca para auxiliar no controle de permissões de usuários
    'braces',
    # Biblioteca para implantação do SQLAlchemy ao sistema
    'aldjemy',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# SESSION_COOKIE_AGE = 60*5 # 5 minutes
# SESSION_SAVE_EVERY_REQUEST = True

ROOT_URLCONF = 'proceg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proceg.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE'   : CONFIG['ENGINE'],
        'NAME'     : CONFIG['NAME'],
        'USER'     : CONFIG['USER'],
        'PASSWORD' : CONFIG['PASSWORD'],
        'HOST'     : CONFIG['HOST'],
        'PORT'     : CONFIG['PORT'],
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = CONFIG['LANGUAGE_CODE']

TIME_ZONE = CONFIG['TIME_ZONE']

USE_I18N = CONFIG['USE_I18N']

USE_TZ = CONFIG['USE_TZ']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = CONFIG['STATIC_URL']

STATIC_ROOT = CONFIG['STATIC_ROOT']

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "login"

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
    },
    "select2": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# SITE_ID = CONFIG['SITE_ID']