# Generated by Django 4.0.4 on 2022-08-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acesso_Restrito', '0001_initial'),
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VI_endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('rua', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('00', 'Estrangeiro (Foreign)')], max_length=2, verbose_name='Estado')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_cidade')),
            ],
            options={
                'verbose_name': 'VI - Endereço',
            },
        ),
        migrations.CreateModel(
            name='VI_os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField()),
                ('justificativa', models.TextField()),
                ('data_ida', models.DateField(verbose_name='Data (ida)')),
                ('horario_ida', models.TimeField(help_text='hh:mm', verbose_name='Horário (ida)')),
                ('data_volta', models.DateField(verbose_name='Data (volta)')),
                ('horario_volta', models.TimeField(help_text='hh:mm', verbose_name='Horário (volta)')),
                ('anexos', models.FileField(help_text='Espaço destinado à apresentação de documentos obrigatórios e acessórios à realização das viagens (justificativa formal, cronograma, folders, declarações diversas, etc)', max_length=255, upload_to='upload')),
                ('status', models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('P', 'Pendente')], default='P', max_length=1, verbose_name='Alterar Status')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Curso.cm_curso')),
                ('destino_ida', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='local_ida', to='Viagens.vi_endereco', verbose_name='Destino (ida)')),
                ('destino_volta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='local_volta', to='Viagens.vi_endereco', verbose_name='Destino (volta)')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coordenador', to='Acesso_Restrito.cm_pessoa')),
                ('viajante', models.ManyToManyField(help_text='Selecione um ou mais', to='Acesso_Restrito.cm_pessoa', verbose_name='Viajante(s)')),
            ],
            options={
                'verbose_name': 'VI - OS',
                'verbose_name_plural': 'VI - OS',
            },
        ),
    ]
