# Generated by Django 4.0.4 on 2022-10-13 13:42

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import procead.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acesso_Restrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SI_ies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=45)),
                ('telefone1', models.CharField(max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'SI - IES',
                'verbose_name_plural': 'SI - IES',
            },
        ),
        migrations.CreateModel(
            name='SI_mantenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=200, verbose_name='Responsável')),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, verbose_name='CNPJ')),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('00', 'Estrangeiro (Foreign)')], max_length=2, verbose_name='UF')),
                ('telefone1', models.CharField(max_length=20, validators=[procead.validators.validate_national_phone_number], verbose_name='Telefone')),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True, validators=[procead.validators.validate_national_phone_number], verbose_name='Telefone secundário (opcional)')),
                ('email', models.EmailField(max_length=254)),
                ('instancia', models.CharField(choices=[('E', 'Estadual'), ('F', 'Federal'), ('M', 'Municipal')], max_length=10, verbose_name='Tipo de instância')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_cidade')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'SI - Mantenedor',
                'verbose_name_plural': 'SI - Mantenedores',
            },
        ),
        migrations.CreateModel(
            name='CM_polo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('C', 'Cancelado'), ('P', 'Publicado'), ('S', 'Suspenso'), ('E', 'Em análise')], max_length=1)),
                ('telefone1', models.CharField(max_length=20, verbose_name='Telefone')),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone opcional')),
                ('email_institucional', models.EmailField(max_length=254)),
                ('email_opcional', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('rua', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('00', 'Estrangeiro (Foreign)')], max_length=2)),
                ('latitude', models.CharField(max_length=11)),
                ('longitude', models.CharField(max_length=11)),
                ('classificacao_seed', models.CharField(blank=True, choices=[('L', 'L - Polo com interrupção de entrada de estudantes nos cursos que necessitam de laboratório'), ('R', 'R - Polo com interrupção de entradas de estudantes'), ('S', 'S - Polo com infraestrutura suficiente'), ('T', 'T - Polo com recomendação de melhoria')], max_length=500, null=True, verbose_name='Classificação SEED')),
                ('distancia_JF', models.PositiveIntegerField(blank=True, help_text='(Km)', null=True, validators=[procead.validators.validate_positive], verbose_name='Distância do polo a Juiz de Fora')),
                ('tempo_viagem', models.CharField(blank=True, help_text='hh:mm', max_length=45, null=True, verbose_name='Tempo de viagem partindo de Juiz de Fora')),
                ('dia_funcionamento_inicio', models.CharField(blank=True, choices=[('dom', 'Domingo'), ('seg', 'Segunda'), ('ter', 'Terça'), ('qua', 'Quarta'), ('qui', 'Quinta'), ('sex', 'Sexta'), ('sab', 'Sábado')], max_length=3, null=True, verbose_name='Dia de funcionamento (início)')),
                ('dia_funcionamento_fim', models.CharField(blank=True, choices=[('dom', 'Domingo'), ('seg', 'Segunda'), ('ter', 'Terça'), ('qua', 'Quarta'), ('qui', 'Quinta'), ('sex', 'Sexta'), ('sab', 'Sábado')], max_length=3, null=True, verbose_name='Dia de funcionamento (fim)')),
                ('horario_funcionamento_inicio', models.TimeField(blank=True, help_text='hh:mm', null=True, verbose_name='Horário de funcionamento (início)')),
                ('horario_funcionamento_fim', models.TimeField(blank=True, help_text='hh:mm', null=True, verbose_name='Horário de funcionamento (fim)')),
                ('apresentacao', models.TextField(blank=True, null=True, verbose_name='Apresentação')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_cidade')),
                ('coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_pessoa')),
                ('ies_vinculadas', models.ManyToManyField(to='Polo.si_ies', verbose_name='IES vinculadas')),
                ('mantenedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Polo.si_mantenedor')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'CM - Polo',
            },
        ),
    ]
