# Generated by Django 4.0.4 on 2022-08-03 19:09

from django.db import migrations, models
import procead.validators


class Migration(migrations.Migration):

    dependencies = [
        ('Polo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cm_polo',
            name='distancia_JF',
            field=models.PositiveIntegerField(blank=True, help_text='(Km)', null=True, validators=[procead.validators.validate_positive], verbose_name='Distância do polo a Juiz de Fora'),
        ),
    ]
