# Generated by Django 4.0.4 on 2022-08-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polo', '0002_remove_cm_polo_latitude_remove_cm_polo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cm_polo',
            name='latitude',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='cm_polo',
            name='longitude',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
