# Generated by Django 4.0.4 on 2022-08-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polo', '0003_cm_polo_latitude_cm_polo_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cm_polo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cm_polo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
