# Generated by Django 4.0.4 on 2022-08-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polo', '0004_alter_cm_polo_latitude_alter_cm_polo_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cm_polo',
            name='cidade',
            field=models.CharField(max_length=255),
        ),
    ]
