# Generated by Django 4.0.4 on 2022-08-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polo', '0005_alter_cm_polo_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_mantenedor',
            name='cidade',
            field=models.CharField(max_length=255),
        ),
    ]
