# Generated by Django 4.0.4 on 2022-08-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polo', '0006_alter_si_mantenedor_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_mantenedor',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
