# Generated by Django 4.0.4 on 2022-10-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Curso', '0001_initial'),
        ('Acesso_Restrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FI_bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
            ],
            options={
                'verbose_name': 'CM - Pessoa/Bolsa',
                'verbose_name_plural': 'CM - Pessoas/Bolsas',
            },
        ),
        migrations.CreateModel(
            name='CM_pessoa_bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Financeiro.fi_bolsa')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Curso.cm_curso')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_pessoa')),
            ],
            options={
                'verbose_name': 'FI - Bolsa',
            },
        ),
    ]
