# Generated by Django 4.0.4 on 2022-08-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cm_curso',
            name='email',
            field=models.EmailField(default='fisica@fisica.ufjf.br', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
