# Generated by Django 4.0.4 on 2022-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0003_si_curso_oferta_ano_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='si_curso_oferta',
            name='ano_oferta',
        ),
        migrations.RemoveField(
            model_name='si_curso_oferta',
            name='numero_oferta',
        ),
        migrations.AddField(
            model_name='si_curso_oferta',
            name='oferta',
            field=models.PositiveIntegerField(default=2022000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pr_edital',
            name='edital_string',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='pr_edital',
            name='num_edital',
            field=models.PositiveIntegerField(verbose_name='Edital número'),
        ),
    ]
