# Generated by Django 4.0.4 on 2022-08-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0004_remove_si_curso_oferta_ano_oferta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr_edital',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='pr_edital',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='pr_edital',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Curso.cm_curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pr_edital',
            name='data_cadastro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
