# Generated by Django 4.0.4 on 2022-08-08 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import localflavor.br.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CM_banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'CM - Banco',
                'ordering': [django.db.models.functions.text.Lower('nome')],
            },
        ),
        migrations.CreateModel(
            name='CM_cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=100)),
                ('uf_cidade', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('00', 'Estrangeiro (Foreign)')], max_length=2)),
            ],
            options={
                'verbose_name': 'CM - Cidade',
            },
        ),
        migrations.CreateModel(
            name='CM_dados_bancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=15, verbose_name='Agência')),
                ('digito_verificador_agencia', models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito Verificador')),
                ('conta', models.CharField(max_length=15, verbose_name='Conta')),
                ('digito_verificador_conta', models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito Verificador')),
                ('operacao', models.CharField(blank=True, max_length=5, null=True, verbose_name='Operação')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_banco')),
            ],
            options={
                'verbose_name': 'CM - Dados Bancários',
                'verbose_name_plural': 'CM - Dados Bancários',
            },
        ),
        migrations.CreateModel(
            name='CM_pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CM - País',
                'verbose_name_plural': 'CM - Países',
            },
        ),
        migrations.CreateModel(
            name='CM_pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome/Nome Social')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('00', 'Estrangeiro (Foreign)')], max_length=2, verbose_name='UF')),
                ('ddd1', models.CharField(max_length=4, verbose_name='DDD')),
                ('telefone1', models.CharField(max_length=20, verbose_name='Telefone')),
                ('ddd2', models.CharField(max_length=4, verbose_name='DDD')),
                ('telefone2', models.CharField(max_length=20, verbose_name='Telefone Celular')),
                ('email', models.EmailField(max_length=254)),
                ('descricao_deficiencia', models.TextField(blank=True, null=True, verbose_name='Descrição de Deficiência (opcional)')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_cidade')),
                ('pais', models.ForeignKey(default=21, on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_pais', verbose_name='País')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CM - Pessoa',
            },
        ),
        migrations.CreateModel(
            name='CM_pessoa_documentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.CharField(blank=True, max_length=8, null=True)),
                ('pispasep', models.CharField(blank=True, max_length=12, null=True)),
                ('data_pispasep', models.DateField(blank=True, null=True)),
                ('profissao', models.CharField(max_length=100, verbose_name='Profissão')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=20, verbose_name='Número do Documento')),
                ('data_emissao_documento', models.DateField(verbose_name='Data de Emissão')),
                ('orgao_expeditor_documento', models.CharField(max_length=30, verbose_name='Órgão Expeditor')),
                ('uf_nascimento', models.CharField(max_length=2, verbose_name='UF de Nascimento')),
                ('nacionalidade', models.CharField(default='Brasileiro(a)', max_length=30)),
                ('estado_civil', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Separado(a)', 'Separado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('União Estável', 'União Estável')], max_length=20, verbose_name='Estado Civil')),
                ('nome_conjuge', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do(a) cônjuge')),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(max_length=200, verbose_name='Nome da Mãe')),
                ('data_cadastramento', models.DateTimeField()),
                ('data_ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('area_ultimo_curso_superior', models.CharField(choices=[('B', 'Biológicas'), ('E', 'Exatas'), ('H', 'Humanas')], max_length=1, verbose_name='Área do último curso superior')),
                ('ultimo_curso_titulacao', models.CharField(max_length=200, verbose_name='Último curso de titulação')),
                ('instituicao_titulacao', models.CharField(max_length=200, verbose_name='Nome da Instituição de Titulação')),
                ('banco', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_dados_bancarios')),
                ('cidade_nascimento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_cidade', verbose_name='Cidade de Nascimento')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_pessoa')),
            ],
            options={
                'verbose_name': 'CM - Pessoa - Documentação',
            },
        ),
        migrations.CreateModel(
            name='CM_associa_grupo_permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.group')),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.permission')),
            ],
            options={
                'verbose_name': 'CM - Associa Grupo/Permissao',
                'verbose_name_plural': 'CM - Associa Grupo/Permissoes',
            },
        ),
    ]
