# Generated by Django 4.0.4 on 2022-08-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acesso_Restrito', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CM_associa_grupo_permissao',
        ),
    ]
