# Generated by Django 4.0.4 on 2022-08-03 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acesso_Restrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cm_pessoa',
            name='pais',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_pais', verbose_name='País'),
        ),
    ]
