# Generated by Django 4.0.4 on 2022-08-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acesso_Restrito', '0003_cm_cidade_latitude_cm_cidade_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cm_cidade',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='cm_cidade',
            name='longitude',
        ),
    ]
