# Generated by Django 4.0.4 on 2022-08-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acesso_Restrito', '0007_alter_cm_pessoa_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cm_pessoa_documentacao',
            name='cidade_nascimento',
            field=models.CharField(max_length=255, verbose_name='Cidade de Nascimento'),
        ),
    ]
