# Generated by Django 4.0.4 on 2022-08-24 12:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acesso_Restrito', '0009_delete_cm_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('richText', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
