# Generated by Django 4.0.4 on 2022-08-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail do Setor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome_setor',
            field=models.CharField(max_length=50, verbose_name='Nome do Setor'),
        ),
    ]
