# Generated by Django 4.0.4 on 2022-08-03 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acesso_Restrito', '0002_alter_cm_pessoa_pais'),
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_siga', models.CharField(max_length=30)),
                ('tipo_curso', models.CharField(choices=[('gra', 'Graduação'), ('esp', 'Especialização'), ('mes', 'Mestrado'), ('dou', 'Doutorado'), ('ext', 'Extensão'), ('cur', 'Curso Livre')], max_length=3)),
                ('curso_ou_departamento_disciplina', models.CharField(max_length=255, verbose_name='Curso/Departamento da disciplina')),
                ('ano_semestre', models.CharField(max_length=6)),
                ('turma', models.CharField(max_length=3)),
                ('conteudo_passado', models.BooleanField()),
                ('modo_inscricao_alunos', models.CharField(choices=[('ime', 'Imediatamente'), ('pos', 'Posteriormente')], max_length=3)),
                ('atividades_inicio', models.DateField()),
                ('atividades_fim', models.DateField()),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=1)),
                ('ultima_atualizacao', models.DateField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_pessoa', verbose_name='Responsável')),
            ],
        ),
    ]
