# Generated by Django 4.0.4 on 2022-08-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acesso_Restrito', '0001_initial'),
        ('Ticket', '0002_alter_setor_email_alter_setor_nome_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='tipo_curso',
            field=models.CharField(choices=[('gra', 'Graduação'), ('esp', 'Especialização'), ('mes', 'Mestrado'), ('dou', 'Doutorado'), ('ext', 'Extensão'), ('cur', 'Curso Livre')], max_length=3, verbose_name='Tipo de Curso'),
        ),
        migrations.CreateModel(
            name='SolicitacaoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_responsavel', models.CharField(max_length=255, verbose_name='Professor Responsável')),
                ('siape', models.CharField(max_length=64, verbose_name='SIAPE')),
                ('unidade_lotacao', models.CharField(max_length=50, verbose_name='Unidade de Lotação')),
                ('nome_disciplina', models.CharField(max_length=255, verbose_name='Nome da Disciplina')),
                ('tipo_curso', models.CharField(choices=[('gra', 'Graduação'), ('esp', 'Especialização'), ('mes', 'Mestrado'), ('dou', 'Doutorado'), ('ext', 'Extensão'), ('cur', 'Curso Livre')], max_length=3, verbose_name='Tipo de Curso')),
                ('caracteristicas', models.CharField(choices=[('UAB', 'UAB'), ('Não UAB', 'Não UAB'), ('ERE', 'ERE'), ('Híbrido', 'Híbrido'), ('Gratuito', 'Gratuito')], max_length=8, verbose_name='Características')),
                ('qtd_disciplinas', models.PositiveIntegerField(verbose_name='Quantidade de Disciplinas')),
                ('inscricoes_inicio', models.DateField(verbose_name='Início das Inscrições')),
                ('inscrições_fim', models.DateField(verbose_name='Fim das Inscrições')),
                ('curso_inicio', models.DateField(verbose_name='Início do Curso')),
                ('curso_fim', models.DateField(verbose_name='Fim do Curso')),
                ('professores', models.PositiveIntegerField()),
                ('tutores', models.PositiveIntegerField()),
                ('demais_colaboradores', models.PositiveIntegerField()),
                ('alunos', models.PositiveIntegerField()),
                ('criacao_AVA', models.BooleanField(blank=True, default=False, verbose_name='Criação de AVA')),
                ('matricula_alunos', models.BooleanField(blank=True, default=False, verbose_name='Matrícula de Alunos')),
                ('capacitacao_interlocutores', models.BooleanField(blank=True, default=False, verbose_name='Capacitação de Interlocutores*')),
                ('outra', models.TextField(blank=True, null=True)),
                ('producao_material', models.BooleanField(blank=True, default=False, verbose_name='Acionamento do setor de produção de material do CEAD')),
                ('assessoria_comunicacao', models.BooleanField(blank=True, default=False, verbose_name='Assessoria de comunicação para sua divulgação')),
                ('ambiente_pre_formatado', models.BooleanField(blank=True, default=False, help_text='O CEAD disponibiliza um Ambiente Modelo Pré Formatado para graduação e pós**', verbose_name='Seu curso/disciplina deseja ambiente pré formatado?')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_pessoa')),
            ],
        ),
    ]
