# Generated by Django 4.0.4 on 2022-08-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_solicitacaodisciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaodisciplina',
            name='ano_semestre',
        ),
        migrations.RemoveField(
            model_name='solicitacaodisciplina',
            name='curso_ou_departamento_disciplina',
        ),
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='ano',
            field=models.CharField(default=2022, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='categoria',
            field=models.CharField(choices=[('SIGA UFJF', 'SIGA UFJF'), ('SIGA UAB', 'SIGA UAB'), ('UFJF Livre', 'UFJF Livre')], default='SIGA UFJF', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='curso_disciplina',
            field=models.CharField(default='Física', max_length=255, verbose_name='A qual curso pertence a disciplina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='departamento_disciplina',
            field=models.CharField(default='DEPFIS', max_length=255, verbose_name='A qual departamento pertence a disciplina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='nome_disciplina',
            field=models.CharField(default='Especialização em Morte Natural', max_length=255, verbose_name='Nome da Disciplina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='semestre',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=3, max_length=1, verbose_name='Período'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='unidade_lotacao',
            field=models.CharField(default='Unidade de Lotação 1', max_length=50, verbose_name='Unidade de Lotação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='codigo_siga',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Código SIGA'),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='conteudo_passado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Favor informar a disciplina, código, ano, semestre e turma a importar'),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='modo_inscricao_alunos',
            field=models.CharField(choices=[('ime', 'Imediatamente'), ('pos', 'Posteriormente')], max_length=3, verbose_name='Alunos constantes naa FAE (SIGA) devem ser inscritos'),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='turma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Turma (ex.: A, B, C)'),
        ),
    ]
