# Generated by Django 4.0.4 on 2022-08-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_alter_solicitacaodisciplina_tipo_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaocurso',
            old_name='inscrições_fim',
            new_name='inscricoes_fim',
        ),
        migrations.RemoveField(
            model_name='solicitacaocurso',
            name='nome_disciplina',
        ),
        migrations.AddField(
            model_name='solicitacaocurso',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaocurso',
            name='nome_curso',
            field=models.CharField(default='Curso', max_length=255, verbose_name='Nome do Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaocurso',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('E', 'Em Andamento'), ('P', 'Pendente'), ('F', 'Fechado')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaocurso',
            name='ultima_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaocurso',
            name='siape',
            field=models.CharField(max_length=7, verbose_name='SIAPE'),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='siape',
            field=models.CharField(max_length=7, verbose_name='SIAPE'),
        ),
    ]
