# Generated by Django 4.0.4 on 2022-08-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acesso_Restrito', '0002_alter_cm_pessoa_pais'),
        ('Ticket', '0004_alter_solicitacaodisciplina_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaodisciplina',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='professor_responsavel',
            field=models.CharField(default='Zezin', max_length=255, verbose_name='Professor Responsável'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='siape',
            field=models.CharField(default='1234', max_length=64, verbose_name='SIAPE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='ultima_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
