# Generated by Django 4.0.4 on 2022-08-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_rename_inscrições_fim_solicitacaocurso_inscricoes_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaodisciplina',
            name='grupos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='categoria',
            field=models.CharField(choices=[('EAD', 'EAD'), ('FC', 'Flexibilização Curricular'), ('Outro', 'Outro')], max_length=5),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='conteudo_passado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Favor informar o nome breve da disciplina a importar'),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='turma',
            field=models.CharField(default='A', max_length=12),
            preserve_default=False,
        ),
    ]
