# Generated by Django 4.0.4 on 2022-08-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0005_solicitacaodisciplina_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='grupos',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
