# Generated by Django 4.0.4 on 2022-08-04 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acesso_Restrito', '0002_alter_cm_pessoa_pais'),
        ('Ticket', '0006_alter_solicitacaodisciplina_curso_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='curso_disciplina',
            field=models.CharField(max_length=255, verbose_name='A qual curso pertence a disciplina'),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acesso_Restrito.cm_pessoa', verbose_name='Professor Responsável'),
        ),
    ]
