# Generated by Django 4.0.4 on 2022-08-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0006_alter_solicitacaodisciplina_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocurso',
            name='capacitacao_interlocutores',
            field=models.BooleanField(blank=True, default=False, verbose_name='Capacitação de Interlocutores'),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='categoria',
            field=models.CharField(choices=[('SIGA/UAB', 'Correspondência no SIGA/UAB'), ('SIGA/Flex', 'Correspondência no SIGA/Flexibilização Curricular'), ('Livre', 'Sem Correspondência no SIGA/Curso Livre')], max_length=9),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='semestre',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
    ]
