# Generated by Django 4.0.4 on 2022-08-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0008_solicitacaocurso_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemsolicitacao',
            options={'verbose_name': 'Mensagem - Solicitação', 'verbose_name_plural': 'Mensagens - Solicitção'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaocurso',
            options={'verbose_name': 'Solicitação de Curso', 'verbose_name_plural': 'Solicitações de Curso'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaodisciplina',
            options={'verbose_name': 'Solicitação de Disciplina', 'verbose_name_plural': 'Solicitações de Disciplina'},
        ),
    ]
